#include "ratchet/differ.h"
#include "ratchet/parser.h"
#include "ratchet/patcher.h"
#include "ratchet/registry.h"
#include "ratchet/compressor.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static int failures = 0;
#define CHECK(x) do { if (!(x)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #x); failures++; return; } } while (0)
static void make_op(RatchetOperation *op, uint8_t type, uint32_t off, uint32_t len, const uint8_t *data) { memset(op, 0, sizeof(*op)); op->type = type; op->offset = off; op->length = len; op->data = (uint8_t *)data; }
static void roundtrip_case(const uint8_t *base, size_t bs, const uint8_t *target, size_t ts) { RatchetBuffer diff; RatchetBuffer out; RatchetRegistry reg; CHECK(ratchet_diff_to_bytes(base, bs, target, ts, "b", "t", &diff) == RATCHET_OK); ratchet_registry_init(&reg); CHECK(ratchet_apply_diff_bytes(diff.data, diff.size, &reg, base, bs, &out) == RATCHET_OK); CHECK(out.size == ts); CHECK(ts == 0 || memcmp(out.data, target, ts) == 0); ratchet_buffer_free(&out); ratchet_registry_free(&reg); ratchet_buffer_free(&diff); }
static void test_round_small(void){ const uint8_t b[]="abcd"; const uint8_t t[]="abXYcd"; roundtrip_case(b,4,t,6); }
static void test_round_empty_base(void){ const uint8_t t[]="hello"; roundtrip_case((const uint8_t *)"",0,t,5); }
static void test_round_empty_target(void){ const uint8_t b[]="hello"; roundtrip_case(b,5,(const uint8_t *)"",0); }
static void test_round_large(void){ uint8_t b[128],t[200]; size_t i; for(i=0;i<128;i++)b[i]=(uint8_t)i; for(i=0;i<200;i++)t[i]=(uint8_t)(i*3u); roundtrip_case(b,128,t,200); }
static void test_crc_reject_header(void){ RatchetBuffer d; const uint8_t b[]="abc",t[]="xyz"; CHECK(ratchet_diff_to_bytes(b,3,t,3,"b","t",&d)==RATCHET_OK); d.data[20]^=1u; CHECK(ratchet_verify_diff(d.data,d.size)==RATCHET_ERROR_CRC); ratchet_buffer_free(&d); }
static void test_crc_reject_record(void){ RatchetBuffer d; const uint8_t b[]="abc",t[]="xyz"; CHECK(ratchet_diff_to_bytes(b,3,t,3,"b","t",&d)==RATCHET_OK); d.data[d.size-1]^=1u; CHECK(ratchet_verify_diff(d.data,d.size)==RATCHET_ERROR_CRC); ratchet_buffer_free(&d); }
static void test_copy_valid(void){ RatchetOperationList ops; RatchetOperation op; RatchetBuffer out; RatchetRegistry reg; const uint8_t b[]="abcdef"; ratchet_operation_list_init(&ops); make_op(&op,RATCHET_OP_COPY,1,3,NULL); CHECK(ratchet_operation_list_push(&ops,&op)==RATCHET_OK); ratchet_registry_init(&reg); CHECK(ratchet_apply_operations(&ops,&reg,b,6,&out)==RATCHET_OK); CHECK(out.size==9); CHECK(memcmp(out.data+6,"bcd",3)==0); ratchet_buffer_free(&out); ratchet_registry_free(&reg); ratchet_operation_list_free(&ops); }
static void test_insert_grow(void){ RatchetOperationList ops; RatchetOperation op; RatchetBuffer out; RatchetRegistry reg; const uint8_t b[]="abc"; const uint8_t x[]="ZZZZ"; ratchet_operation_list_init(&ops); make_op(&op,RATCHET_OP_INSERT,0,4,x); CHECK(ratchet_operation_list_push(&ops,&op)==RATCHET_OK); ratchet_registry_init(&reg); CHECK(ratchet_apply_operations(&ops,&reg,b,3,&out)==RATCHET_OK); CHECK(out.size==7); ratchet_buffer_free(&out); ratchet_registry_free(&reg); ratchet_operation_list_free(&ops); }
static void test_delete_shrink(void){ RatchetOperationList ops; RatchetOperation op; RatchetBuffer out; RatchetRegistry reg; const uint8_t b[]="abcdef"; ratchet_operation_list_init(&ops); make_op(&op,RATCHET_OP_DELETE,2,2,NULL); CHECK(ratchet_operation_list_push(&ops,&op)==RATCHET_OK); ratchet_registry_init(&reg); CHECK(ratchet_apply_operations(&ops,&reg,b,6,&out)==RATCHET_OK); CHECK(out.size==4); CHECK(memcmp(out.data,"abef",4)==0); ratchet_buffer_free(&out); ratchet_registry_free(&reg); ratchet_operation_list_free(&ops); }
static void test_mixed_ops(void){ RatchetOperationList ops; RatchetOperation op; RatchetBuffer out; RatchetRegistry reg; const uint8_t b[]="abcdef"; const uint8_t x[]="XY"; ratchet_operation_list_init(&ops); make_op(&op,RATCHET_OP_INSERT,0,2,x); CHECK(ratchet_operation_list_push(&ops,&op)==RATCHET_OK); make_op(&op,RATCHET_OP_COPY,0,2,NULL); CHECK(ratchet_operation_list_push(&ops,&op)==RATCHET_OK); make_op(&op,RATCHET_OP_DELETE,1,1,NULL); CHECK(ratchet_operation_list_push(&ops,&op)==RATCHET_OK); ratchet_registry_init(&reg); CHECK(ratchet_apply_operations(&ops,&reg,b,6,&out)==RATCHET_OK); CHECK(out.size==9); ratchet_buffer_free(&out); ratchet_registry_free(&reg); ratchet_operation_list_free(&ops); }
static RatchetBuffer diff_from_ops(RatchetOperationList *ops){ RatchetBuffer b; ratchet_buffer_init(&b); if(ratchet_write_diff(ops,&b)!=RATCHET_OK){ printf("FAIL %s:%d: ratchet_write_diff\n", __FILE__, __LINE__); failures++; } return b; }
static void test_chain_one(void){ RatchetOperationList child,parent; RatchetOperation op; RatchetBuffer cb,out; RatchetRegistry reg; const uint8_t base[]="abc"; const uint8_t x[]="D"; ratchet_operation_list_init(&child); make_op(&op,RATCHET_OP_INSERT,0,1,x); CHECK(ratchet_operation_list_push(&child,&op)==RATCHET_OK); cb=diff_from_ops(&child); ratchet_operation_list_init(&parent); memset(&op,0,sizeof(op)); op.type=RATCHET_OP_CHAIN; strcpy(op.version,"v1"); CHECK(ratchet_operation_list_push(&parent,&op)==RATCHET_OK); ratchet_registry_init(&reg); CHECK(ratchet_registry_put(&reg,"v1",cb.data,cb.size)==RATCHET_OK); CHECK(ratchet_apply_operations(&parent,&reg,base,3,&out)==RATCHET_OK); CHECK(out.size==4); ratchet_buffer_free(&out); ratchet_registry_free(&reg); ratchet_buffer_free(&cb); ratchet_operation_list_free(&child); ratchet_operation_list_free(&parent); }
static void test_chain_two(void){ RatchetOperationList c1,c2,p; RatchetOperation op; RatchetBuffer b1,b2,out; RatchetRegistry reg; const uint8_t base[]="abc"; const uint8_t x[]="D"; const uint8_t y[]="E"; ratchet_operation_list_init(&c1); make_op(&op,RATCHET_OP_INSERT,0,1,x); CHECK(ratchet_operation_list_push(&c1,&op)==RATCHET_OK); b1=diff_from_ops(&c1); ratchet_operation_list_init(&c2); memset(&op,0,sizeof(op)); op.type=RATCHET_OP_CHAIN; strcpy(op.version,"v1"); CHECK(ratchet_operation_list_push(&c2,&op)==RATCHET_OK); make_op(&op,RATCHET_OP_INSERT,0,1,y); CHECK(ratchet_operation_list_push(&c2,&op)==RATCHET_OK); b2=diff_from_ops(&c2); ratchet_operation_list_init(&p); memset(&op,0,sizeof(op)); op.type=RATCHET_OP_CHAIN; strcpy(op.version,"v2"); CHECK(ratchet_operation_list_push(&p,&op)==RATCHET_OK); ratchet_registry_init(&reg); CHECK(ratchet_registry_put(&reg,"v1",b1.data,b1.size)==RATCHET_OK); CHECK(ratchet_registry_put(&reg,"v2",b2.data,b2.size)==RATCHET_OK); CHECK(ratchet_apply_operations(&p,&reg,base,3,&out)==RATCHET_OK); CHECK(out.size==5); ratchet_buffer_free(&out); ratchet_registry_free(&reg); ratchet_buffer_free(&b1); ratchet_buffer_free(&b2); ratchet_operation_list_free(&c1); ratchet_operation_list_free(&c2); ratchet_operation_list_free(&p); }
static void test_identical_diff(void){ const uint8_t b[]="same same"; RatchetOperationList ops; CHECK(ratchet_diff_buffers(b,9,b,9,"b","t",&ops)==RATCHET_OK); CHECK(ops.count==2); CHECK(ops.items[0].type==RATCHET_OP_COPY); CHECK(ops.items[1].type==RATCHET_OP_DELETE); ratchet_operation_list_free(&ops); }
static void test_no_common(void){ const uint8_t b[]="abcd"; const uint8_t t[]="WXYZ"; RatchetOperationList ops; CHECK(ratchet_diff_buffers(b,4,t,4,"b","t",&ops)==RATCHET_OK); CHECK(ops.count==2); CHECK(ops.items[0].type==RATCHET_OP_INSERT); CHECK(ops.items[1].type==RATCHET_OP_DELETE); ratchet_operation_list_free(&ops); }
static void test_repeated_runs(void){ const uint8_t b[]="AAAAAAAABBBB"; const uint8_t t[]="AAAAAAAACCCCBBBB"; roundtrip_case(b,12,t,16); }
static void test_compress_round(void){ const uint8_t d[]="AAAAAAAABCDABCDZZZZZZ"; RatchetBuffer c,o; CHECK(ratchet_compress_literal(d,sizeof(d)-1,&c)==RATCHET_OK); CHECK(ratchet_decompress_literal(c.data,c.size,&o)==RATCHET_OK); CHECK(o.size==sizeof(d)-1); CHECK(memcmp(o.data,d,o.size)==0); ratchet_buffer_free(&c); ratchet_buffer_free(&o); }
static void test_parse_invalid_magic(void){ uint8_t d[160]={0}; RatchetOperationList ops; CHECK(ratchet_parse_diff(d,sizeof(d),&ops)==RATCHET_ERROR_INVALID); }
static void test_parse_truncated(void){ uint8_t d[2]={0}; RatchetOperationList ops; CHECK(ratchet_parse_diff(d,sizeof(d),&ops)==RATCHET_ERROR_INVALID); }
static void test_delete_bounds(void){ RatchetOperationList ops; RatchetOperation op; RatchetBuffer out; RatchetRegistry reg; const uint8_t b[]="abc"; ratchet_operation_list_init(&ops); make_op(&op,RATCHET_OP_DELETE,2,5,NULL); CHECK(ratchet_operation_list_push(&ops,&op)==RATCHET_OK); ratchet_registry_init(&reg); CHECK(ratchet_apply_operations(&ops,&reg,b,3,&out)==RATCHET_ERROR_BOUNDS); ratchet_registry_free(&reg); ratchet_operation_list_free(&ops); }
static void test_copy_bounds(void){ RatchetOperationList ops; RatchetOperation op; RatchetBuffer out; RatchetRegistry reg; const uint8_t b[]="abc"; ratchet_operation_list_init(&ops); make_op(&op,RATCHET_OP_COPY,2,5,NULL); CHECK(ratchet_operation_list_push(&ops,&op)==RATCHET_OK); ratchet_registry_init(&reg); CHECK(ratchet_apply_operations(&ops,&reg,b,3,&out)==RATCHET_ERROR_BOUNDS); ratchet_registry_free(&reg); ratchet_operation_list_free(&ops); }
static void test_registry_missing(void){ RatchetRegistry r; const uint8_t *d; size_t s; ratchet_registry_init(&r); CHECK(ratchet_registry_get(&r,"x",&d,&s)==RATCHET_ERROR_NOT_FOUND); ratchet_registry_free(&r); }
static void test_registry_put_get(void){ RatchetRegistry r; const uint8_t x[]={1,2}; const uint8_t *d; size_t s; ratchet_registry_init(&r); CHECK(ratchet_registry_put(&r,"x",x,2)==RATCHET_OK); CHECK(ratchet_registry_get(&r,"x",&d,&s)==RATCHET_OK); CHECK(s==2 && d[0]==1); ratchet_registry_free(&r); }
static void test_write_parse(void){ RatchetOperationList ops,parsed; RatchetOperation op; RatchetBuffer b; const uint8_t x[]="abc"; ratchet_operation_list_init(&ops); make_op(&op,RATCHET_OP_INSERT,0,3,x); CHECK(ratchet_operation_list_push(&ops,&op)==RATCHET_OK); CHECK(ratchet_write_diff(&ops,&b)==RATCHET_OK); CHECK(ratchet_parse_diff(b.data,b.size,&parsed)==RATCHET_OK); CHECK(parsed.count==1); ratchet_operation_list_free(&parsed); ratchet_buffer_free(&b); ratchet_operation_list_free(&ops); }
static void test_long_insert(void){ uint8_t t[300]; size_t i; for(i=0;i<300;i++)t[i]=(uint8_t)('A'+(i%26)); roundtrip_case((const uint8_t *)"base",4,t,300); }
static void test_zero_length_insert_skip(void){ RatchetOperationList ops; CHECK(ratchet_diff_buffers((const uint8_t *)"abc",3,(const uint8_t *)"abc",3,"b","t",&ops)==RATCHET_OK); CHECK(ops.count==0 || ops.items[0].length>0); ratchet_operation_list_free(&ops); }
int main(void){
void (*tests[])(void)={test_round_small,test_round_empty_base,test_round_empty_target,test_round_large,test_crc_reject_header,test_crc_reject_record,test_copy_valid,test_insert_grow,test_delete_shrink,test_mixed_ops,test_chain_one,test_chain_two,test_identical_diff,test_no_common,test_repeated_runs,test_compress_round,test_parse_invalid_magic,test_parse_truncated,test_delete_bounds,test_copy_bounds,test_registry_missing,test_registry_put_get,test_write_parse,test_long_insert,test_zero_length_insert_skip};
size_t i; for(i=0;i<sizeof(tests)/sizeof(tests[0]);i++) tests[i](); if(failures){printf("%d failures\n",failures); return 1;} printf("25 tests passed\n"); return 0; }
