#include "ratchet/differ.h"
#include "ratchet/parser.h"
#include <stdio.h>
#include <string.h>
static int write_seed(const char *name, const uint8_t *data, size_t size){ char path[256]; FILE *f; snprintf(path,sizeof(path),"fuzz/corpus/patch_fuzzer/%s",name); f=fopen(path,"wb"); if(!f) return 1; if(size && fwrite(data,1,size,f)!=size){fclose(f);return 1;} fclose(f); return 0; }
static int write_diff_seed(const char *name,const uint8_t *base,size_t bs,const uint8_t *target,size_t ts){ RatchetBuffer out; if(ratchet_diff_to_bytes(base,bs,target,ts,"base","target",&out)!=RATCHET_OK) return 1; if(write_seed(name,out.data,out.size)){ratchet_buffer_free(&out);return 1;} ratchet_buffer_free(&out); return 0; }
static int write_ops_seed(const char *name,RatchetOperationList *ops){ RatchetBuffer out; if(ratchet_write_diff(ops,&out)!=RATCHET_OK) return 1; if(write_seed(name,out.data,out.size)){ratchet_buffer_free(&out);return 1;} ratchet_buffer_free(&out); return 0; }
static void op_make(RatchetOperation *op,uint8_t type,uint32_t off,uint32_t len,const uint8_t *data){ memset(op,0,sizeof(*op)); op->type=type; op->offset=off; op->length=len; op->data=(uint8_t *)data; }
int main(void){ const uint8_t base[]="ABCDEFGHIJKLMNOPQRSTUVWXYZ012345"; RatchetOperationList ops,child,mid; RatchetOperation op; const uint8_t a[]="hello"; const uint8_t b[]="worldworld"; int rc=0; rc|=write_diff_seed("insert_min_1.bin",(const uint8_t *)"",0,a,5); rc|=write_diff_seed("insert_min_2.bin",(const uint8_t *)"",0,b,10); rc|=write_diff_seed("copy_only_1.bin",base,32,base,8); rc|=write_diff_seed("copy_only_2.bin",base,32,base+4,12); ratchet_operation_list_init(&ops); op_make(&op,RATCHET_OP_INSERT,0,5,(const uint8_t *)"AAAAA"); rc|=ratchet_operation_list_push(&ops,&op); op_make(&op,RATCHET_OP_COPY,4,8,NULL); rc|=ratchet_operation_list_push(&ops,&op); rc|=write_ops_seed("mixed_insert_copy_1.bin",&ops); ratchet_operation_list_free(&ops); ratchet_operation_list_init(&ops); op_make(&op,RATCHET_OP_INSERT,0,9,(const uint8_t *)"BBBBBBBBB"); rc|=ratchet_operation_list_push(&ops,&op); op_make(&op,RATCHET_OP_INSERT,0,4,(const uint8_t *)"CCCC"); rc|=ratchet_operation_list_push(&ops,&op); op_make(&op,RATCHET_OP_COPY,10,6,NULL); rc|=ratchet_operation_list_push(&ops,&op); rc|=write_ops_seed("mixed_insert_copy_2.bin",&ops); ratchet_operation_list_free(&ops); ratchet_operation_list_init(&child); op_make(&op,RATCHET_OP_INSERT,0,3,(const uint8_t *)"ONE"); rc|=ratchet_operation_list_push(&child,&op); rc|=write_ops_seed("chain_child_one.bin",&child); ratchet_operation_list_init(&ops); memset(&op,0,sizeof(op)); op.type=RATCHET_OP_CHAIN; strcpy(op.version,"chain_child_one"); rc|=ratchet_operation_list_push(&ops,&op); op_make(&op,RATCHET_OP_INSERT,0,1,(const uint8_t *)"X"); rc|=ratchet_operation_list_push(&ops,&op); rc|=write_ops_seed("chain_one.bin",&ops); ratchet_operation_list_free(&ops); ratchet_operation_list_free(&child); ratchet_operation_list_init(&child); op_make(&op,RATCHET_OP_INSERT,0,3,(const uint8_t *)"TWO"); rc|=ratchet_operation_list_push(&child,&op); rc|=write_ops_seed("chain_child_two_a.bin",&child); ratchet_operation_list_init(&mid); memset(&op,0,sizeof(op)); op.type=RATCHET_OP_CHAIN; strcpy(op.version,"chain_child_two_a"); rc|=ratchet_operation_list_push(&mid,&op); op_make(&op,RATCHET_OP_INSERT,0,3,(const uint8_t *)"MID"); rc|=ratchet_operation_list_push(&mid,&op); rc|=write_ops_seed("chain_child_two_b.bin",&mid); ratchet_operation_list_init(&ops); memset(&op,0,sizeof(op)); op.type=RATCHET_OP_CHAIN; strcpy(op.version,"chain_child_two_b"); rc|=ratchet_operation_list_push(&ops,&op); op_make(&op,RATCHET_OP_INSERT,0,3,(const uint8_t *)"END"); rc|=ratchet_operation_list_push(&ops,&op); rc|=write_ops_seed("chain_two.bin",&ops); ratchet_operation_list_free(&child); ratchet_operation_list_free(&mid); ratchet_operation_list_free(&ops); return rc ? 1 : 0; }
